#!/bin/bash
# $1 in $2 out
# $3 fg $4 bg
sed "s/\(fill=\)\"#000\"/\1\"$(clrmgr.py -x $3)\"/g" $1 > tmp.svg && \
#inkscape tmp.svg -b "$(clrmgr.py -x $4)" -w 32 -h 32 -o $2
inkscape tmp.svg -b "$(clrmgr.py -x $4)" -o $2

#rm tmp.svg
